### ISSUE TITLE
error on 'update' for the table name with schema 

### ISSUE THREAD

**Issue by 8026787** [sapienlab/dbh-pg#13]
```
using(db.conn(), function (conn) {
    var table_name = 'aggregator.sectors';
    return conn
        .begin()
        .then(function(){
            this.fetchOne('select * from "' + table_name + '" limit 1').then(function(record){
            return {id: record.id};
        })
        .then(function(params){
            console.log(params); //{ id: 250 }
            return this.update( table_name , {name:null}, params);
            // Unhandled rejection error: relation "aggregator.sectors" does not exist
        })
        .then(function(){ this.rollback(); })
    });
});
```

If I wrap table name with quotas (`'"aggregator.sectors"'`) I get 
```
Unhandled rejection error: zero-length delimited identifier at or near """"
``` 
And it only for the `update` function, the `fetch` goes ok

**Comment by roro89** [comment]
Hi, Thank you for reporting this error!

This is related to https://github.com/sapienlab/dbh-pg/issues/12#issuecomment-153723570

I'll fix it within hours :)

**Comment by roro89** [comment]
This bug should be solved with the [v2.1.0](https://github.com/sapienlab/dbh-pg/pull/15)

Please, comment if is Ok to close this issue :)

**Comment by roro89** [comment]
Reading this issue more clearly, I think I misunderstood.

Such behavior is good, according to the current implementation of the code. For security reasons, both [`insert`](https://github.com/sapienlab/dbh-pg/blob/master/API.md#insertstring-table-object-row---string-returning----promise) and [`update`](https://github.com/sapienlab/dbh-pg/blob/master/API.md#updatestring-table-object-data-object-where---string-returning----promise), [`exists`](https://github.com/sapienlab/dbh-pg/blob/master/API.md#existsstring-table-object-where---promise) and [`count`](https://github.com/sapienlab/dbh-pg/blob/master/API.md#countstring-table---object-where----promise) automatically wrap the table name with quotation marks.

Tip: You can see the SQL generated by activating the debug mode [`.verbose`](https://github.com/sapienlab/dbh-pg/blob/master/API.md#new-dbhobject-settings---object-driver----dbh)

```javascript
var db = new DBH ('postgres:postgres@//localhost/db2test');
db.verbose = true; // <- Because true, a log is send to the console
                   //    with the generated SQL before execute
```

I update the API Doc to clarify this points.

**Comment by 8026787** [comment]
So i guess the problem is here:

```
this.update( 'aggregator.sectors' , {name:null}, params);
```

```
UPDATE "aggregator.sectors" SET "event_sector_id"=$1 WHERE "foreign_id"=$2 AND "gateway_id"=$3 RETURNING *
```
I suppose `"aggregator.sectors" ` should be `"aggregator"."sectors" `

**Comment by 8026787** [comment]
I’ve solved it this way by now:
```
this.update( 'aggregator"."sectors' , {name:null}, params);
```
Pero creo que es mejor permitir a los usuarios encargarse de las comillas por sí mismos )

Thank you!

**Comment by roro89** [comment]
You are right, is not a good idea to automatically enquote the table name... unless it is done right (this is not the case).

This is a breaking change, so I think that we need a new major version (v3.0.0). In that case:

```javascript
this.update( '"aggregator"."sectors"' , {name:null}, params);
``` 
will be the right way.

I promise to release this new version this weekend or earlier.

**Comment by 8026787** [comment]
Thank you!

**Comment by rgcl** [comment]
The new version 3.x was released. Thanks for your comments!
